name: UPDATE MAP4.JSON

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # setiap 1 jam

permissions:
  contents: write

jobs:
  fetch_m3u8:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repo publik
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Clone repo privat config
        run: |
          git clone --depth=1 https://x-access-token:${{ secrets.TOKEN_PRIVATE }}@github.com/${{ secrets.REPO_PRIVATE }} configrepo
          cp configrepo/926data_file.txt $HOME/926data_file.txt

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install blinker==1.4 selenium selenium-wire beautifulsoup4 webdriver-manager
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run cinbiang.py script
        env:
          CHROME_BIN: /usr/bin/google-chrome
        run: python cinbiang.py

      - name: Commit & Push changes if any
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add map4.json

          if git diff --cached --quiet; then
            echo "âœ… Tidak ada perubahan, skip push."
          else
            git commit -m "ðŸ”„ Update map4.json [bot]"
            git pull --rebase origin main || git pull --rebase origin master
            git push origin HEAD
          fi
