name: UPDATE MAP4.JSON

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # setiap 1 jam

permissions:
  contents: write

jobs:
  fetch_m3u8:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repo publik
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Clone repo privat config
        run: |
          git clone --depth=1 https://x-access-token:${{ secrets.TOKEN_PRIVATE }}@github.com/${{ secrets.REPO_PRIVATE }} configrepo
          cp configrepo/926data_file.txt $HOME/926data_file.txt

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --force-reinstall blinker==1.4
          pip install selenium selenium-wire beautifulsoup4
          sudo apt-get update
          sudo apt-get install -y chromium-browser || true
          sudo apt-get install -y chromium chromium-driver

      - name: Run cinbiang.py script
        env:
          CHROME_BIN: /usr/bin/chromium
          CHROMEDRIVER_PATH: /usr/bin/chromedriver
        run: python cinbiang.py

      - name: Commit & Push changes if any
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add map4.json

          if git diff --cached --quiet; then
            echo "âœ… Tidak ada perubahan, skip push."
          else
            git commit -m "ðŸ”„ Update map4.json [bot]"
            git pull --rebase origin main || git pull --rebase origin master
            git push origin HEAD
          fi
