name: â° Update Streamnya Map

on:
  schedule:
    - cron: "0 * * * *"   # setiap jam
  workflow_dispatch:       # bisa run manual

jobs:
  update-map:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: ğŸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: ğŸ“¦ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests selenium

      - name: ğŸ“ Ambil file konfigurasi dari repo privat
        shell: bash
        run: |
          git clone --depth=1 https://x-access-token:${{ secrets.TOKEN_PRIVATE }}@github.com/${{ secrets.REPO_PRIVATE }} configrepo
          cp configrepo/sterame3data_file.txt $HOME/sterame3data_file.txt

      - name: â–¶ï¸ Jalankan script Python
        run: |
          python cinhodal1.py

      - name: Commit & Push changes if any
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add map5.json

          if git diff --cached --quiet; then
              echo "âœ… Tidak ada perubahan, skip push."
          else
              git commit -m "ğŸ”„ Update map5.json [bot]"
              git pull --rebase origin main || git pull --rebase origin master
              git push origin HEAD
           fi
