name: Cvvp Auto Fetch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Setiap 1 jam
jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Google Chrome Stable
        run: |
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb

      - name: Install Python dependencies
        run: |
          pip install requests

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Install Playwright
        run: |
          pip install playwright
          python -m playwright install-deps
          python -m playwright install chromium

      - name: Start virtual display
        run: |
          export DISPLAY=:99
          Xvfb :99 -ac -screen 0 1280x720x16 &
          sleep 2

      - name: üìÅ Ambil file konfigurasi dari repo privat
        run: |
          git clone --depth=1 https://x-access-token:${{ secrets.TOKEN_PRIVATE }}@github.com/${{ secrets.REPO_PRIVATE }} configrepo
          cp configrepo/cvvpdata_file.txt $HOME/cvvpdata_file.txt

      - name: ‚ñ∂Ô∏è Jalankan script Python
        run: |
          python CHINVVP.py

      - name: üöÄ Commit & Push changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add map8.json || true

          if git diff --staged --quiet; then
            echo "‚úÖ Tidak ada perubahan, skip push."
          else
            git commit -m "üîÑ Update map8.json [bot]"
            git fetch origin master
            git rebase origin/master || git rebase --abort
            git push origin HEAD:master
          fi
