name: ğŸ”„ Generate map3.json setiap jam

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-map3:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo publik ini
        uses: actions/checkout@v3

      - name: ğŸ Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: ğŸ“ Ambil file konfigurasi dari repo privat
        shell: bash
        run: |
          git clone --depth=1 https://x-access-token:${{ secrets.TOKEN_PRIVATE }}@github.com/${{ secrets.REPO_PRIVATE }} configrepo
          cp configrepo/aebabami_file.txt $HOME/aebabami_file.txt

      - name: ğŸ“¦ Install dependensi
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pytz

      - name: ğŸš€ Jalankan script Python
        run: python RINIATE.py

      - name: Push map3.json ke Repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add map3.json
          if git diff --cached --quiet; then
            echo "âœ… Tidak ada perubahan"
          else
            git commit -m "auto: update map3.json"
            git pull --rebase origin master
            git push origin master
          fi
